console.log('eduardo');
console.log('daniel');
var x = 1;
var y = 2;
var z = x+y;
console.log(z);
console.log('eduardo');
console.log('daniel');
var x = 1;
var y = 2;
var z = x+y;
console.log(z);
console.log('eduardo');
console.log('daniel');
var x = 1;
var y = 2;
var z = x+y;
console.log(z);
console.log('eduardo');
console.log('daniel');
var x = 1;
var y = 2;
var z = x+y;
console.log(z);